# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1ff77f37375f9a6603f22ecd67e5e832"
name = "AMD Checkout"
handle = "honey-birdette-checkout-amd"
application_url = "https://honey-birdette-checkout-amd.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "amd-checkout-2024.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, write_customers, customer_read_customers, customer_write_customers, write_discounts, write_orders, read_metaobjects, write_cart_transforms, write_metaobject_definitions, write_delivery_customizations, read_themes, write_themes, read_files, write_files"

[auth]
redirect_urls = [
  "https://honey-birdette-checkout-amd.onrender.com/auth/callback",
  "https://honey-birdette-checkout-amd.onrender.com/auth/shopify/callback",
  "https://honey-birdette-checkout-amd.onrender.com/api/auth/callback"
]

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = ["metaobjects/update", "metaobjects/delete"]
  uri = "/webhooks"
  filter = "type:lubricant_bundle"

[pos]
embedded = false

[discount.metafields.app.function-configuration]
type = "json"
name = "Function configuration"
access.admin = "merchant_read_write"
access.storefront = "none"


[metafields]
api_version = "2026-01"

[customer.metafields.app.customer_birthday_day]
name = "Birthday Day"
description = "Stores the day of the customer's birthday"
type = "number_integer"

[customer.metafields.app.customer_birthday_month]
name = "Birthday Month"
description = "Stores the month of the customer's birthday"
type = "number_integer"

[app_proxy]
url = "https://honey-birdette-birthday-app.onrender.com"
subpath = "omeno-birthday"
prefix = "apps"
