api_version = "2026-01"

[[extensions]]
name = "t:name"
handle = "update-us-shipping-po-and-afo-boxes"
type = "function"
uid = "37138a01-be7d-2851-cbb7-d89a1a9db06bf094e9ca"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.delivery-options.transform.run"
  input_query = "src/cart_delivery_options_transform_run.graphql"
  export = "cart-delivery-options-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
