api_version = "2026-01"

[[extensions]]
name = "t:name"
handle = "block-discount-codes-with-gift-cards"
type = "function"
uid = "12bde554-24b7-5c41-7a28-ec5cbc6e4a9962cd576c"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.validations.generate.run"
  input_query = "src/cart_validations_generate_run.graphql"
  export = "cart-validations-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
