api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "toy-pwp-discount"
type = "function"
uid = "7c017c99-3dc5-900c-cd94-cd4049e176aa"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/cart_lines_discounts_generate_run.graphql"
  export = "cart-lines-discounts-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
