api_version = "2026-01"

[[extensions]]
name = "t:name"
handle = "quantity-10-limit"
type = "function"
uid = "daa1ac67-6734-fe72-259e-26a2384c244b3bdcf7d5"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.validations.generate.run"
  input_query = "src/cart_validations_generate_run.graphql"
  export = "cart-validations-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
