api_version = "2025-07"

[[extensions]]
name = "omeno-birthday-banner"
handle = "omeno-birthday-banner"
type = "ui_extension"
uid = "2bd0aa92-06c2-54b2-6059-a86286eefb081514f1d3"

[[extensions.targeting]]
module = "./src/OrderStatusBlock.tsx"
target = "customer-account.profile.block.render"

[extensions.capabilities]
api_access = true
network_access = true

[access_scopes]
scopes = "read_customers, write_customers, read_metaobjects, write_metaobjects"

[[extensions.metafields]]
namespace = "custom"
key = "customer_birthday_day"

[[extensions.metafields]]
namespace = "custom"
key = "customer_birthday_month"

[[extensions.metafields]]
namespace = "custom"
key = "tags"

