# Script generated by Playwright on October 10 2023 at 23:01pm AEDT.
# This script is licenced for use *only* on honey-birdette-2.myshopify.com.
# Learn more at https://playwrightapp.com

class O
  def initialize(ca)
    @q = ca
  end

  def bf(cart, line_item)
    @q.any? { |a| a.all? { |bz| bg(bz[:n], bz[:by], bz[:r], cart, line_item) } }
  end

  def bg(n, by, r, cart, line_item)
    false
  end
end

class K < O
  def bg(n, by, r, cart, line_item)
    case n
    when 'cm'
      case by
      when 'ay'
        (line_item.variant.product.tags & [r]).empty?
      else
        !(line_item.variant.product.tags & [r]).empty?
      end
    else
      false
    end
  end
end

class H < O
  def bg(n, by, r, cart, line_item)
    return false if cart.customer.nil?
    false
  end
end

class I
  def initialize(message, bw)
    @j = message
  end

  def c(line_item)
    bj = an(line_item)
    if bj <= line_item.line_price
      line_item.change_line_price(bj, message: @j)
    end
  end

  def an(line_item)
    line_item.line_price
  end

  def self.ak(y)
    case y[:ab]
    when 'cp', 'cs'
      M.new(y[:z] || y[:cp], y[:x] || y[:message], !!y[:bw], y[:ab] === 'cs')
    when 'ct', 'cu'
      B.new(y[:dl] || y[:ct], y[:x] || y[:message], !!y[:bw], y[:ab] === 'cu')
    when 'cv'
      J.new(y[:dn] || y[:cv], y[:x] || y[:message], !!y[:bw])
    else
      nil
    end
  end

  private

  def cw(line_item)
    (line_item.variant.compare_at_price || line_item.variant.price) * line_item.quantity
  end
end

class M < I
  def initialize(cp, message, bw, cx = false)
    @l = Decimal.new(cp) / 100.0
    @r = cx
    super(message, bw)
  end

  def an(line_item)
    original_line_price = @r ? cw(line_item) : line_item.original_line_price
    cr = Money.new(cents: (original_line_price.cents / line_item.quantity * @l)) * line_item.quantity
    original_line_price - cr
  end
end

class B < I
  def initialize(ct, message, bw, cx = false)
    @s = Money.new(cents: ct)
    @r = cx
    super(message, bw)
  end

  def an(line_item)
    original_line_price = @r ? cw(line_item) : line_item.original_line_price
    original_line_price - (@s * line_item.quantity)
  end
end

class J < I
  def initialize(cv, message, bw)
    @e = Money.new(cents: cv)
    super(message, bw)
  end

  def an(line_item)
    @e * line_item.quantity
  end
end

class G
  def initialize(bm = {})
    @k = bm
  end

  def run(cart)
  end
end

class F < G
  def run(cart, ai)
    return [] if ai.empty?
    return ai unless @k[:discount_code].nil? or (!cart.discount_code.nil? and (cart.discount_code.code.upcase == @k[:discount_code]))
    return ai unless @k[:bi].nil? or (cart.subtotal_price >= Money.new(cents: @k[:bi]))

    p = []
    matrix = @k[:q].map do |o|
      cb = K.new(o[:ca])
      p << I.ak(o[:discount].merge(reject_discount: @k[:bw]))
      ai.map do |line_item|
        cb.bf(cart, line_item) ? line_item.quantity : 0
      end
    end

    bh = matrix.map { |o| o.reduce(0, :+) }.min
    return ai unless (bh > 0)

    cd = []
    be = ai.map { |_| matrix.map { 0 } }

    (1..bh).each do |n|
      bu = ai.map { 0 }
      ce = []
      matrix.each_with_index do |line_items, y|
        bt = @k[:q][y][:quantity].to_i
        bs = bt
        cf = []
        line_items.each_with_index do |br, x|
          bv = [[br - bu[x], 0].max, bs].min
          bs -= bv
          bu[x] += bv
          cf << bv
        end
        ce << cf
      end

      break unless az(@k[:q], ce)

      cd << ce
      ce.each_with_index do |line_items, y|
        line_items.each_with_index do |quantity, x|
          matrix[y][x] = [matrix[y][x] - bu[x], 0].max
          be[x][y] += quantity
        end
      end
    end

    return ai if cd.empty?

    f = []
    be.each_with_index do |q, x|
      q.each_with_index do |quantity, y|
        next if quantity == 0
        if ai[x].quantity > quantity
          bundle_line_item = ai[x].split(take: quantity)
          cart.line_items << bundle_line_item
        else
          bundle_line_item = ai[x]
        end
        unless p[y].nil?
          p[y].c(bundle_line_item)
        end
        f << bundle_line_item
      end
    end

    ai.reject { |ah| f.include?(ah) }
  end

  private

  def az(q, ce)
    cg = []
    ce.each_with_index do |line_items, y|
      cg << (line_items.reduce(0, :+) == q[y][:quantity].to_i)
    end
    cg.all?
  end
end

cq = Input.cart

[
  F.new({
    :q => [
      {
        :ca => [[{ :n => "cm", :by => "aw", :r => "promo-bundle--antibac" }]],
        :discount => { :ct => "", :message => "", :cp => 0, :cv => "500", :ab => "none" },
        :quantity => "1"
      },
      {
        :ca => [[{ :n => "cm", :by => "aw", :r => "promo-bundle--silk-deluxe" }]],
        :discount => { :ct => "", :message => "", :cp => 0, :ab => "none" },
        :quantity => "1"
      },
      {
        :ca => [[{ :n => "cm", :by => "aw", :r => "promo-bundle--o" }]],
        :discount => { :message => "Deluxe Bundle", :cp => 0, :cv => "1000", :ab => "none" },
        :quantity => 1
      },
      {
        :ca => [[{ :n => "cm", :by => "aw", :r => "promo-bundle--edible-lubricant" }]],
        :discount => { :ct => "2000", :message => "Platinum Bundle", :cp => 0, :cv => "2000", :ab => "ct" },
        :quantity => 1
      }
    ],
    :discount_code => nil,
    :bi => nil,
    :bw => false
  }),
  F.new({
    :q => [
      {
        :ca => [[{ :n => "cm", :by => "aw", :r => "promo-bundle--antibac" }]],
        :discount => { :ct => "", :message => "", :cp => 0, :cv => "500", :ab => "none" },
        :quantity => "1"
      },
      {
        :ca => [[{ :n => "cm", :by => "aw", :r => "promo-bundle--silk-deluxe" }]],
        :discount => { :ct => "500", :message => "Premium Bundle", :cp => 0, :ab => "none" },
        :quantity => "1"
      },
      {
        :ca => [
          [{ :n => "cm", :by => "aw", :r => "promo-bundle--o" }],
          [{ :n => "cm", :by => "aw", :r => "pants" }]
        ],
        :discount => { :ct => "1000", :message => "Delux Bundle", :cp => 0, :cv => "1000", :ab => "ct" },
        :quantity => 1
      }
    ],
    :discount_code => nil,
    :bi => nil,
    :bw => false
  }),
  F.new({
    :q => [
      {
        :ca => [[{ :n => "cm", :by => "aw", :r => "promo-bundle--antibac" }]],
        :discount => { :ct => "", :message => "", :cp => 0, :cv => "500", :ab => "none" },
        :quantity => "1"
      },
      {
        :ca => [[{ :n => "cm", :by => "aw", :r => "promo-bundle--silk-deluxe" }]],
        :discount => { :ct => "500", :message => "Premium Bundle", :cp => 0, :ab => "ct" },
        :quantity => "1"
      }
    ],
    :discount_code => nil,
    :bi => nil,
    :bw => false
  })
].reduce(cq.line_items.sort_by { |line_item| -line_item.variant.price }) do |ai, campaign|
  campaign.run(cq, ai)
end
