api_version = "2026-01"

[[extensions]]
name = "t:name"
handle = "limit-1"
type = "function"
uid = "6c529a81-b097-6b81-40b3-211b4821067caeb00917"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.validations.generate.run"
  input_query = "src/cart_validations_generate_run.graphql"
  export = "cart-validations-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
