api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "gift-with-purchase-discount"
type = "function"
uid = "78947530-fbe3-4324-bee7-92a2ed122417"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/cart_lines_discounts_generate_run.graphql"
  export = "cart-lines-discounts-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
