api_version = "2026-01"
[[extensions]]
# Change the merchant-facing name of the extension in locales/en.default.json
name = "t:name"
description = "t:description"
handle = "byo-bundle-discount-order-ui"
uid = "byo-bundle-discount-order-ui-uid-placeholder"
type = "ui_extension"
# Only 1 target can be specified for each Admin block extension
[[extensions.targeting]]
module = "./src/DiscountFunctionSettings.jsx"
target = "admin.discount-details.function-settings.render"

[[extensions.metafields]]
namespace = "$app"
key = "function-configuration"


