api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "lubricant-bundle-transform"
type = "function"
uid = "778d351f-d7b7-dd9e-d4d9-9663c28ea973f8e49bbe"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
