# Learn more about configuring your checkout UI extension:
# https://shopify.dev/api/checkout-extensions/checkout/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2024-07"

[[extensions]]
name = "Product Upsell"
handle = "product-upsell"
type = "ui_extension"


[[extensions.targeting]]
module = "./src/Checkout.tsx"
target = "purchase.checkout.block.render"

[extensions.capabilities]
api_access = true
network_access = true
block_progress = true

[extensions.settings]
  [[extensions.settings.fields]]
  key = "product"
  type = "variant_reference"
  name = "Select Variant"
  description = "Choose a product variant for the upsell"

  [[extensions.settings.fields]]
  key = "title"
  type = "multi_line_text_field"
  name = "Title"
  description = "Enter a title."
  
  [[extensions.settings.fields]]
  key = "description"
  type = "multi_line_text_field"
  name = "Description"
  description = "Enter a description."


  [[extensions.settings.fields]]
  key = "gwp"
  type = "boolean"
  name = "Gift With Purchase?"
  description = "Must make the product $0 or add an automatic discout or Shopify Function."
  default = false
