# Learn more about configuring your checkout UI extension:
# https://shopify.dev/api/checkout-extensions/checkout/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2025-01"

[[extensions]]
name = "Product Upsells V2"
handle = "Product-upsells-V2"
type = "ui_extension"


# Controls where in Shopify your extension will be injected,
# and the file that contains your extension’s source code. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/extension-targets-overview

[[extensions.targeting]]
module = "./src/Checkout.tsx"
target = "purchase.checkout.block.render"

[extensions.capabilities]
# Gives your extension access to directly query Shopify’s storefront API.
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#api-access
api_access = true

# Gives your extension access to make external network calls, using the
# JavaScript `fetch()` API. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#network-access
# network_access = true

# Loads metafields on checkout resources, including the cart,
# products, customers, and more. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#metafields

# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_key"
# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_other_key"

# Defines settings that will be collected from merchants installing
# your extension. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#settings-definition

# [extensions.settings]
# [[extensions.settings.fields]]
# key = "banner_title"
# type = "single_line_text_field"
# name = "Banner title"
# description = "Enter a title for the banner"


# The settings below are just examples—customize them as needed.


# shopify.extension.toml
[settings]

  # --- Product 1 ---
  [[extensions.settings.fields]]
  key = "product1"
  type = "variant_reference"
  name = "PRODUCT #1"
  description = "Choose a product variant for the upsell"

  [[extensions.settings.fields]]
  key = "product1_is_gwp"
  type = "boolean"
  name = "Is GWP?"
  description = "Check if this upsell is a GWP"

  [[extensions.settings.fields]]
  key = "product1_is_giftbox"
  type = "boolean"
  name = "Is Giftbox?"
  description = "Check if this upsell is a Giftbox"

  [[extensions.settings.fields]]
  key = "product1_title"
  type = "single_line_text_field"
  name = "Title"
  description = "Enter a custom upsell title for product 1"

  [[extensions.settings.fields]]
  key = "product1_description"
  type = "single_line_text_field"
  name = "Description"
  description = "Enter a custom upsell description for product 1"


  # --- Product 2 ---
  [[extensions.settings.fields]]
  key = "product2"
  type = "variant_reference"
  name = "PRODUCT #2"
  description = "Choose a product variant for the upsell"

  [[extensions.settings.fields]]
  key = "product2_is_gwp"
  type = "boolean"
  name = "Is GWP?"
  description = "Check if this upsell is a GWP"

  [[extensions.settings.fields]]
  key = "product2_is_giftbox"
  type = "boolean"
  name = "Is Giftbox?"
  description = "Check if this upsell is a Giftbox"

  [[extensions.settings.fields]]
  key = "product2_title"
  type = "single_line_text_field"
  name = "Title"
  description = "Enter a custom upsell title for product 2"

  [[extensions.settings.fields]]
  key = "product2_description"
  type = "single_line_text_field"
  name = "Description"
  description = "Enter a custom upsell description for product 2"


  # --- Product 3 ---
  [[extensions.settings.fields]]
  key = "product3"
  type = "variant_reference"
    name = "PRODUCT #3"
  description = "Choose a product variant for the upsell"

  [[extensions.settings.fields]]
  key = "product3_is_gwp"
  type = "boolean"
  name = "Is GWP?"
  description = "Check if this upsell is a GWP"

  [[extensions.settings.fields]]
  key = "product3_is_giftbox"
  type = "boolean"
  name = "Is Giftbox?"
  description = "Check if this upsell is a Giftbox"

  [[extensions.settings.fields]]
  key = "product3_title"
  type = "single_line_text_field"
  name = "Title"
  description = "Enter a custom upsell title for product 3"

  [[extensions.settings.fields]]
  key = "product3_description"
  type = "single_line_text_field"
  name = "Description"
  description = "Enter a custom upsell description for product 3"


  # --- Product 4 ---
  [[extensions.settings.fields]]
  key = "product4"
  type = "variant_reference"
  name = "PRODUCT #4"
  description = "Choose a product variant for the upsell"

  [[extensions.settings.fields]]
  key = "product4_is_gwp"
  type = "boolean"
  name = "Is GWP?"
  description = "Check if this upsell is a GWP"

  [[extensions.settings.fields]]
  key = "product4_is_giftbox"
  type = "boolean"
  name = "Is Giftbox?"
  description = "Check if this upsell is a Giftbox"

  [[extensions.settings.fields]]
  key = "product4_title"
  type = "single_line_text_field"
  name = "Title"
  description = "Enter a custom upsell title for product 4"

  [[extensions.settings.fields]]
  key = "product4_description"
  type = "single_line_text_field"
  name = "Description"
  description = "Enter a custom upsell description for product 4"


