api_version = "2026-01"

[[extensions]]
name = "t:name"
handle = "gift-checker"
type = "function"
uid = "e6c83bc4-a950-9bc0-9dd0-81714064b87193ee877b"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.validations.generate.run"
  input_query = "src/cart_validations_generate_run.graphql"
  export = "cart-validations-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
